/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:d8468f13-8c90-4237-b38d-db6cf14fe5e4',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_Cp8tNY1Eo',
    aws_user_pools_web_client_id: '62n13nhk7bqnmd7qdr8vkbfgnk',
    oauth: {
        domain: 'foodperuwebf8d40262-f8d40262-dev.auth.us-east-1.amazoncognito.com',
        scope: [
            'phone',
            'email',
            'openid',
            'profile',
            'aws.cognito.signin.user.admin'
        ],
        redirectSignIn: 'http://localhost:4200/',
        redirectSignOut: 'http://localhost:4200/',
        responseType: 'code'
    },
    federationTarget: 'COGNITO_USER_POOLS'
};


export default awsmobile;
